export const AnalisysOfCauseTypes = {
    ANALISYS_OF_CAUSE_STATE : "@analisysOfCause/ANALISYS_OF_CAUSE_STATE",
    GET_ANALISYS_SUBJECT_REQUEST : "@analisysOfCause/GET_ANALISYS_SUBJECT_REQUEST",
    GET_ANALISYS_SUBJECT_SUCCESS : "@analisysOfCause/GET_ANALISYS_SUBJECT_SUCCESS",
    GET_ANALISYS_SUBJECT_FAILURE : "@analisysOfCause/GET_ANALISYS_SUBJECT_FAILURE",
    GET_ANALISYS_OF_CAUSE_REQUEST : "@analisysOfCause/GET_ANALISYS_OF_CAUSE_REQUEST",
    GET_ANALISYS_OF_CAUSE_SUCCESS : "@analisysOfCause/GET_ANALISYS_OF_CAUSE_SUCCESS",
    GET_ANALISYS_OF_CAUSE_FAILURE : "@analisysOfCause/GET_ANALISYS_OF_CAUSE_FAILURE",
    ANALISYS_OF_CAUSE_SAVE_REQUEST: "@analisysOfCause/ANALISYS_OF_CAUSE_SAVE_REQUEST",
    ANALISYS_OF_CAUSE_SAVE_SUCCESS: "@analisysOfCause/ANALISYS_OF_CAUSE_SAVE_SUCCESS",
    ANALISYS_OF_CAUSE_SAVE_FAILURE: "@analisysOfCause/ANALISYS_OF_CAUSE_SAVE_FAILURE",
}