export const ReportTypes = {
    RETRIEVE_REPORT_BY_MENU_REQUEST: "@report/RETRIEVE_REPORT_BY_MENU_REQUEST",
    RETRIEVE_REPORT_BY_MENU_SUCCESS: "@report/RETRIEVE_REPORT_BY_MENU_SUCCESS",
    RETRIEVE_REPORT_BY_MENU_FAILURE: "@report/RETRIEVE_REPORT_BY_MENU_FAILURE"
};