export const PreventiveAndCorrectiveTypes = {
    PREVENTIVE_CORRECTIVE_STATE : "@PreventiveAndCorrective/PREVENTIVE_CORRECTIVE_STATE",
    GET_PC_SUBJECT_REQUEST : "@PreventiveAndCorrective/GET_PC_SUBJECT_REQUEST",
    GET_PC_SUBJECT_SUCCESS : "@PreventiveAndCorrective/GET_PC_SUBJECT_SUCCESS",
    GET_PC_SUBJECT_FAILURE : "@PreventiveAndCorrective/GET_PC_SUBJECT_FAILURE",
    GET_PC_REQUEST : "@PreventiveAndCorrective/GET_PC_REQUEST",
    GET_PC_SUCCESS : "@PreventiveAndCorrective/GET_PC_SUCCESS",
    GET_PC_FAILURE : "@PreventiveAndCorrective/GET_ANALISYS_OF_CAUSE_FAILURE",
    PREVENTIVE_CORRECTIVE_SAVE_REQUEST: "@PreventiveAndCorrective/PREVENTIVE_CORRECTIVE_SAVE_REQUEST",
    PREVENTIVE_CORRECTIVE_SAVE_SUCCESS: "@PreventiveAndCorrective/PREVENTIVE_CORRECTIVE_SAVE_SUCCESS",
    PREVENTIVE_CORRECTIVE_SAVE_FAILURE: "@PreventiveAndCorrective/PREVENTIVE_CORRECTIVE_SAVE_FAILURE"
}