export const MenuTypes = {
    MENU_REQUEST: "@Menu/MENU_REQUEST",
    MENU_SUCCESS: "@Menu/MENU_SUCCESS",
    MENU_FAILURE: "@Menu/MENU_FAILURE",
    SUBMENU_REQUEST: "@Menu/SUBMENU_REQUEST",
    SUBMENU_SUCCESS: "@Menu/SUBMENU_SUCCESS",
    SUBMENU_FAILURE: "@Menu/SUBMENU_FAILURE"
}